// Mock data for the inventory management system

export interface InventoryItem {
  id: string;
  name: string;
  sku: string;
  category: string; // Will store category ID
  quantity: number;
  reorderPoint: number;
  inventoryCap?: number; // Maximum stock level
  supplier: string; // Will store supplier ID
  location: string; // Will store location ID
  expirationDate: string | null;
  lastUpdated: string;
  createdAt: string;
  notes: string;
  costPrice: number;
  sellingPrice: number;
}

export const MOCK_INVENTORY: InventoryItem[] = [
  {
    id: "INV-1001",
    name: "Premium Dog Food",
    sku: "SKU100001",
    category: "Food",
    quantity: 42,
    reorderPoint: 20,
    inventoryCap: 100,
    supplier: "PetCo",
    location: "Warehouse A",
    expirationDate: "2024-12-31",
    lastUpdated: "2023-06-15",
    createdAt: "2023-01-10",
    notes: "Best seller, high margin",
    costPrice: 750,
    sellingPrice: 1200,
  },
  {
    id: "INV-1002",
    name: "Cat Litter Box",
    sku: "SKU100002",
    category: "Accessories",
    quantity: 15,
    reorderPoint: 10,
    inventoryCap: 40,
    supplier: "Animal Supplies Inc.",
    location: "Warehouse B",
    expirationDate: null,
    lastUpdated: "2023-05-20",
    createdAt: "2023-01-15",
    notes: "Medium-sized, popular model",
    costPrice: 350,
    sellingPrice: 699,
  },
  {
    id: "INV-1003",
    name: "Bird Cage - Large",
    sku: "SKU100003",
    category: "Accessories",
    quantity: 8,
    reorderPoint: 5,
    inventoryCap: 25,
    supplier: "Pet Food Direct",
    location: "Store Front",
    expirationDate: null,
    lastUpdated: "2023-06-01",
    createdAt: "2023-02-01",
    notes: "Premium model, high quality",
    costPrice: 1200,
    sellingPrice: 2499,
  },
  {
    id: "INV-1004",
    name: "Dog Leash - Leather",
    sku: "SKU100004",
    category: "Accessories",
    quantity: 25,
    reorderPoint: 15,
    inventoryCap: 50,
    supplier: "Animal Supplies Inc.",
    location: "Store Front",
    expirationDate: null,
    lastUpdated: "2023-05-25",
    createdAt: "2023-02-10",
    notes: "Premium quality leather",
    costPrice: 250,
    sellingPrice: 499,
  },
  {
    id: "INV-1005",
    name: "Cat Food - Grain Free",
    sku: "SKU100005",
    category: "Food",
    quantity: 18,
    reorderPoint: 20,
    inventoryCap: 60,
    supplier: "PetCo",
    location: "Warehouse A",
    expirationDate: "2024-11-15",
    lastUpdated: "2023-06-10",
    createdAt: "2023-03-01",
    notes: "Premium brand, increasing demand",
    costPrice: 550,
    sellingPrice: 950,
  },
  {
    id: "INV-1006",
    name: "Fish Tank - 20 Gallon",
    sku: "SKU100006",
    category: "Accessories",
    quantity: 5,
    reorderPoint: 3,
    inventoryCap: 15,
    supplier: "Global Pet Products",
    location: "Warehouse B",
    expirationDate: null,
    lastUpdated: "2023-05-15",
    createdAt: "2023-03-15",
    notes: "Complete with filter and lights",
    costPrice: 1500,
    sellingPrice: 2999,
  },
  {
    id: "INV-1007",
    name: "Hamster Wheel",
    sku: "SKU100007",
    category: "Toys",
    quantity: 30,
    reorderPoint: 15,
    inventoryCap: 60,
    supplier: "Pet Food Direct",
    location: "Store Front",
    expirationDate: null,
    lastUpdated: "2023-06-05",
    createdAt: "2023-04-01",
    notes: "Silent operation, popular model",
    costPrice: 100,
    sellingPrice: 249,
  },
  {
    id: "INV-1008",
    name: "Dog Toy - Squeaky Bone",
    sku: "SKU100008",
    category: "Toys",
    quantity: 45,
    reorderPoint: 20,
    inventoryCap: 80,
    supplier: "Animal Supplies Inc.",
    location: "Warehouse A",
    expirationDate: null,
    lastUpdated: "2023-06-12",
    createdAt: "2023-04-15",
    notes: "Durable rubber material",
    costPrice: 75,
    sellingPrice: 199,
  },
  {
    id: "INV-1009",
    name: "Cat Scratching Post",
    sku: "SKU100009",
    category: "Accessories",
    quantity: 12,
    reorderPoint: 8,
    inventoryCap: 30,
    supplier: "Global Pet Products",
    location: "Store Front",
    expirationDate: null,
    lastUpdated: "2023-05-30",
    createdAt: "2023-05-01",
    notes: "Sisal rope, sturdy base",
    costPrice: 300,
    sellingPrice: 699,
  },
  {
    id: "INV-1010",
    name: "Reptile Heat Lamp",
    sku: "SKU100010",
    category: "Accessories",
    quantity: 7,
    reorderPoint: 5,
    inventoryCap: 20,
    supplier: "Pet Food Direct",
    location: "Warehouse B",
    expirationDate: null,
    lastUpdated: "2023-06-01",
    createdAt: "2023-05-15",
    notes: "UVA/UVB, energy efficient",
    costPrice: 200,
    sellingPrice: 449,
  },
  {
    id: "INV-1011",
    name: "Dog Shampoo - Medicated",
    sku: "SKU100011",
    category: "Grooming",
    quantity: 22,
    reorderPoint: 12,
    inventoryCap: 48,
    supplier: "PetCo",
    location: "Warehouse A",
    expirationDate: "2025-01-15",
    lastUpdated: "2023-06-08",
    createdAt: "2023-06-01",
    notes: "For sensitive skin, vet recommended",
    costPrice: 150,
    sellingPrice: 349,
  },
  {
    id: "INV-1012",
    name: "Bird Seed Mix",
    sku: "SKU100012",
    category: "Food",
    quantity: 35,
    reorderPoint: 20,
    inventoryCap: 70,
    supplier: "Global Pet Products",
    location: "Warehouse A",
    expirationDate: "2024-09-30",
    lastUpdated: "2023-06-10",
    createdAt: "2023-06-02",
    notes: "Premium blend for small birds",
    costPrice: 100,
    sellingPrice: 249,
  },
  {
    id: "INV-1013",
    name: "Fish Food Flakes",
    sku: "SKU100013",
    category: "Food",
    quantity: 40,
    reorderPoint: 25,
    inventoryCap: 80,
    supplier: "PetCo",
    location: "Store Front",
    expirationDate: "2024-10-31",
    lastUpdated: "2023-06-12",
    createdAt: "2023-06-03",
    notes: "For tropical fish, high protein",
    costPrice: 80,
    sellingPrice: 179,
  },
  {
    id: "INV-1014",
    name: "Dog Nail Clippers",
    sku: "SKU100014",
    category: "Grooming",
    quantity: 15,
    reorderPoint: 10,
    inventoryCap: 40,
    supplier: "Animal Supplies Inc.",
    location: "Store Front",
    expirationDate: null,
    lastUpdated: "2023-06-07",
    createdAt: "2023-06-04",
    notes: "Professional grade, safety guard",
    costPrice: 120,
    sellingPrice: 299,
  },
  {
    id: "INV-1015",
    name: "Cat Carrier",
    sku: "SKU100015",
    category: "Accessories",
    quantity: 10,
    reorderPoint: 5,
    inventoryCap: 25,
    supplier: "Global Pet Products",
    location: "Warehouse B",
    expirationDate: null,
    lastUpdated: "2023-06-05",
    createdAt: "2023-06-05",
    notes: "Airline approved, medium size",
    costPrice: 400,
    sellingPrice: 899,
  },
  {
    id: "INV-1016",
    name: "Small Animal Bedding",
    sku: "SKU100016",
    category: "Accessories",
    quantity: 28,
    reorderPoint: 15,
    inventoryCap: 60,
    supplier: "Pet Food Direct",
    location: "Warehouse A",
    expirationDate: "2024-12-31",
    lastUpdated: "2023-06-11",
    createdAt: "2023-06-06",
    notes: "Dust-free, absorbent material",
    costPrice: 120,
    sellingPrice: 249,
  },
  {
    id: "INV-1017",
    name: "Aquarium Plants - Artificial",
    sku: "SKU100017",
    category: "Accessories",
    quantity: 20,
    reorderPoint: 10,
    inventoryCap: 50,
    supplier: "Global Pet Products",
    location: "Store Front",
    expirationDate: null,
    lastUpdated: "2023-06-09",
    createdAt: "2023-06-07",
    notes: "Realistic appearance, set of 5",
    costPrice: 150,
    sellingPrice: 399,
  },
  {
    id: "INV-1018",
    name: "Dog Flea Treatment",
    sku: "SKU100018",
    category: "Medication",
    quantity: 18,
    reorderPoint: 12,
    inventoryCap: 48,
    supplier: "PetCo",
    location: "Office",
    expirationDate: "2025-02-28",
    lastUpdated: "2023-06-12",
    createdAt: "2023-06-08",
    notes: "3-month supply, all sizes",
    costPrice: 350,
    sellingPrice: 699,
  },
  {
    id: "INV-1019",
    name: "Cat Litter - Clumping",
    sku: "SKU100019",
    category: "Accessories",
    quantity: 32,
    reorderPoint: 20,
    inventoryCap: 80,
    supplier: "Animal Supplies Inc.",
    location: "Warehouse A",
    expirationDate: null,
    lastUpdated: "2023-06-13",
    createdAt: "2023-06-09",
    notes: "Odor control, dust-free formula",
    costPrice: 200,
    sellingPrice: 449,
  },
  {
    id: "INV-1020",
    name: "Dog Brush - De-shedding",
    sku: "SKU100020",
    category: "Grooming",
    quantity: 14,
    reorderPoint: 8,
    inventoryCap: 35,
    supplier: "Global Pet Products",
    location: "Store Front",
    expirationDate: null,
    lastUpdated: "2023-06-14",
    createdAt: "2023-06-10",
    notes: "For medium to large breeds",
    costPrice: 180,
    sellingPrice: 399,
  },
  {
    id: "INV-1021",
    name: "Rabbit Pellets",
    sku: "SKU100021",
    category: "Food",
    quantity: 0,
    reorderPoint: 15,
    inventoryCap: 60,
    supplier: "Pet Food Direct",
    location: "Warehouse A",
    expirationDate: "2024-11-30",
    lastUpdated: "2023-06-14",
    createdAt: "2023-06-11",
    notes: "High fiber formula",
    costPrice: 90,
    sellingPrice: 199,
  },
  {
    id: "INV-1022",
    name: "Dog Bed - Large",
    sku: "SKU100022",
    category: "Accessories",
    quantity: 6,
    reorderPoint: 8,
    inventoryCap: 30,
    supplier: "Global Pet Products",
    location: "Warehouse B",
    expirationDate: null,
    lastUpdated: "2023-06-13",
    createdAt: "2023-06-12",
    notes: "Orthopedic foam, machine washable",
    costPrice: 500,
    sellingPrice: 1299,
  },
  {
    id: "INV-1023",
    name: "Cat Wand Toy",
    sku: "SKU100023",
    category: "Toys",
    quantity: 25,
    reorderPoint: 15,
    inventoryCap: 55,
    supplier: "Animal Supplies Inc.",
    location: "Store Front",
    expirationDate: null,
    lastUpdated: "2023-06-11",
    createdAt: "2023-06-13",
    notes: "Interactive play, feather attachment",
    costPrice: 60,
    sellingPrice: 149,
  },
  {
    id: "INV-1024",
    name: "Turtle Food Pellets",
    sku: "SKU100024",
    category: "Food",
    quantity: 12,
    reorderPoint: 8,
    inventoryCap: 35,
    supplier: "PetCo",
    location: "Warehouse A",
    expirationDate: "2024-10-15",
    lastUpdated: "2023-06-12",
    createdAt: "2023-06-14",
    notes: "Floating pellets, vitamin enriched",
    costPrice: 70,
    sellingPrice: 149,
  },
  {
    id: "INV-1025",
    name: "Guinea Pig Hay",
    sku: "SKU100025",
    category: "Food",
    quantity: 0,
    reorderPoint: 10,
    inventoryCap: 40,
    supplier: "Pet Food Direct",
    location: "Warehouse A",
    expirationDate: "2024-09-01",
    lastUpdated: "2023-06-15",
    createdAt: "2023-06-15",
    notes: "Timothy hay, high fiber",
    costPrice: 85,
    sellingPrice: 189,
  },
  {
    id: "INV-1026",
    name: "Automatic Pet Feeder",
    sku: "SKU100026",
    category: "Accessories",
    quantity: 120,
    reorderPoint: 5,
    inventoryCap: 20,
    supplier: "Global Pet Products",
    location: "Warehouse B",
    expirationDate: null,
    lastUpdated: "2023-06-10",
    createdAt: "2023-06-16",
    notes: "Programmable, portion control",
    costPrice: 800,
    sellingPrice: 1699,
  },
  {
    id: "INV-1027",
    name: "Puppy Training Pads",
    sku: "SKU100027",
    category: "Accessories",
    quantity: 38,
    reorderPoint: 20,
    inventoryCap: 80,
    supplier: "Animal Supplies Inc.",
    location: "Store Front",
    expirationDate: null,
    lastUpdated: "2023-06-14",
    createdAt: "2023-06-17",
    notes: "Super absorbent, pack of 50",
    costPrice: 150,
    sellingPrice: 349,
  },
  {
    id: "INV-1028",
    name: "Cat Dental Treats",
    sku: "SKU100028",
    category: "Food",
    quantity: 22,
    reorderPoint: 15,
    inventoryCap: 60,
    supplier: "PetCo",
    location: "Warehouse A",
    expirationDate: "2024-08-31",
    lastUpdated: "2023-06-13",
    createdAt: "2023-06-18",
    notes: "Tartar control, chicken flavor",
    costPrice: 95,
    sellingPrice: 199,
  },
  {
    id: "INV-1029",
    name: "Bird Cage Cleaner",
    sku: "SKU100029",
    category: "Grooming",
    quantity: 14,
    reorderPoint: 10,
    inventoryCap: 40,
    supplier: "Pet Food Direct",
    location: "Office",
    expirationDate: "2025-03-15",
    lastUpdated: "2023-06-12",
    createdAt: "2023-06-19",
    notes: "Non-toxic, biodegradable",
    costPrice: 85,
    sellingPrice: 179,
  },
  {
    id: "INV-1030",
    name: "Dog Training Treats",
    sku: "SKU100030",
    category: "Food",
    quantity: 55,
    reorderPoint: 25,
    inventoryCap: 40,
    supplier: "Animal Supplies Inc.",
    location: "Store Front",
    expirationDate: "2024-07-31",
    lastUpdated: "2023-06-15",
    createdAt: "2023-06-20",
    notes: "Small size, beef flavor",
    costPrice: 100,
    sellingPrice: 229,
  },
];

// Helper to generate stats for the dashboard
export const getInventoryStats = (inventory: typeof MOCK_INVENTORY) => {
  // Total number of items
  const totalItems = inventory.length;

  // Total stock count
  const totalStock = inventory.reduce((sum, item) => sum + item.quantity, 0);

  // Total inventory value (based on cost price)
  const totalValue = inventory.reduce(
    (sum, item) => sum + item.quantity * item.costPrice,
    0
  );

  // Total potential revenue (based on selling price)
  const totalPotentialRevenue = inventory.reduce(
    (sum, item) => sum + item.quantity * item.sellingPrice,
    0
  );

  // Low stock items count
  const lowStockItems = inventory.filter(
    (item) => item.quantity <= item.reorderPoint
  ).length;

  // Category distribution
  const categoryCount: Record<string, number> = {};

  inventory.forEach((item) => {
    const category = item.category;
    categoryCount[category] = (categoryCount[category] || 0) + 1;
  });

  const categoryDistribution = Object.entries(categoryCount)
    .map(([name, count]) => ({ name, count }))
    .sort((a, b) => b.count - a.count);

  return {
    totalItems,
    totalStock,
    totalValue,
    totalPotentialRevenue,
    lowStockItems,
    categoryDistribution,
  };
};
